# name of conda environment
name: alignparse-environment

# channels to install conda dependencies
channels:
  - conda-forge

# conda dependencies
dependencies:
  - python==3.6
  - pip
  # install the following packages with `pip install.`
  - pip:
    - 