# name of conda environment
name: alignparse-environment

# channels to install conda dependencies
channels:
  - conda-forge

# conda dependencies
dependencies:
  - python==3.6
  - minimap2==2.17-r941
  - pip
  # install the current package with `pip install.`
  - pip:
    - .
